branch-defaults:
  master:
    environment: TestDjango
environment-defaults:
  TestDjango:
    branch: null
    repository: null
global:
  application_name: TestDjango
  default_ec2_keyname: test-Django
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  sc: git
  workspace_type: Application
