branch-defaults:
  master:
    environment: test-Django

environment-defaults:
  test-Django:
    branch: null
    repository: null

global:
  application_name: test
  default_ec2_keyname: test-Django
  default_platform: Python 3.7
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  sc: git
  workspace_type: Application
