branch-defaults:
  default:
    environment: test-Django
    group_suffix: null

  master:
    environment: test-Django
    group_suffix: null

environment-defaults:
  test-Django:
    branch: null
    repository: null

global:
  application_name: test
  branch: null
  default_ec2_keyname: test-Django
  default_platform: Python 3.7
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
