# Generated by Django 3.1.4 on 2020-12-17 21:22


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = ('contenttypes', '0002_remove_content_type_name'),

    operations = [
        migrations.CreateModel(
            name='M0',

            fields=[
                ('id',
                 models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),

                ('f0',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Field 0',
                    max_length=255,
                    verbose_name='Field 0')),

                ('polymorphic_ctype',
                 models.ForeignKey(
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='polymorphic_app.m0_set+',
                    to='contenttypes.contenttype'))
            ],

            options={
                'verbose_name': 'M0',
                'verbose_name_plural': 'M0s',
                'db_table': 'M0',
                'default_related_name': 'm0s'
            }
        ),

        migrations.CreateModel(
            name='M1',

            fields=[
                ('m0_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='m1s',
                    serialize=False,
                    to='app.m0')),

                ('f1',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Field 1',
                    max_length=255,
                    verbose_name='Field 1'))
            ],

            options={
                'verbose_name': 'M1',
                'verbose_name_plural': 'M1s',
                'db_table': 'M1',
                'default_related_name': 'm1s'
            },

            bases=('app.m0',)
        ),

        migrations.CreateModel(
            name='M1A',

            fields=[
                ('m1a_m0_ptr',
                 models.OneToOneField(
                    default=None,
                    editable=False,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='m1a',
                    related_query_name='m1a',
                    serialize=False,
                    to='app.m0')),

                ('f1a',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Field 1a',
                    max_length=255,
                    verbose_name='Field 1a'))
            ],

            options={
                'verbose_name': 'M1A',
                'verbose_name_plural': 'M1As',
                'db_table': 'M1A',
                'default_related_name': 'm1as'
            },

            bases=('app.m0',)
        ),

        migrations.CreateModel(
            name='M2',

            fields=[
                ('m1_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='m2s',
                    serialize=False,
                    to='app.m1')),

                ('f2',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Field 2',
                    max_length=255,
                    verbose_name='Field 2'))
            ],

            options={
                'verbose_name': 'M2',
                'verbose_name_plural': 'M2s',
                'db_table': 'M2',
                'default_related_name': 'm2s'
            },

            bases=('app.m1',)
        ),

        migrations.CreateModel(
            name='M2A',

            fields=[
                ('m1a_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='m2as',
                    serialize=False,
                    to='app.m1a')),

                ('f2a',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Field 2a',
                    max_length=255,
                    verbose_name='Field 2a'))
            ],

            options={
                'verbose_name': 'M2A',
                'verbose_name_plural': 'M2As',
                'db_table': 'M2A',
                'default_related_name': 'm2as'
            },

            bases=('app.m1a',)
        ),

        migrations.CreateModel(
            name='M2B',

            fields=[
                ('m1_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='m2bs',
                    serialize=False,
                    to='app.m1')),

                ('m1a_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    related_name='m2bs',
                    to='app.m1a')),

                ('f2b',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Field 2b',
                    max_length=255,
                    verbose_name='Field 2b'))
            ],

            options={
                'verbose_name': 'M2B',
                'verbose_name_plural': 'M2Bs',
                'db_table': 'M2B',
                'default_related_name': 'm2bs'
            },

            bases=('app.m1',
                   'app.m1a')
        ),

        migrations.CreateModel(
            name='M',

            fields=[
                ('id',
                 models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),

                ('fk',
                 models.ForeignKey(
                    blank=True,
                    default=None,
                    help_text='Foreign Key',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='fk_ms',
                    related_query_name='fk_m',
                    to='app.m0',
                    verbose_name='Foreign Key')),

                ('o2o',
                 models.OneToOneField(
                    blank=True,
                    default=None,
                    help_text='One-to-One',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='o2o_m',
                    related_query_name='o2o_m',
                    to='app.m0',
                    verbose_name='One-to-One')),

                ('self_fk',
                 models.ForeignKey(
                    blank=True,
                    default=None,
                    help_text='Self Foreign Key',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='fk_ms',
                    related_query_name='fk_m',
                    to='app.m', verbose_name='Self Foreign Key')),

                ('self_o2o',
                 models.OneToOneField(
                    blank=True,
                    default=None,
                    help_text='Self One-to-One',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='o2o_m',
                    related_query_name='o2o_m',
                    to='app.m',
                    verbose_name='Self One-to-One')),

                ('m2m',
                 models.ManyToManyField(
                    blank=True,
                    db_index=True,
                    default=None,
                    help_text='Many-to-Many',
                    related_name='m2m_ms',
                    related_query_name='m2m_m',
                    to='app.M0',
                    verbose_name='Many-to-Many')),

                ('asym_self_m2m',
                 models.ManyToManyField(
                    blank=True,
                    db_index=True,
                    default=None,
                    help_text='Asymmetrical Self Many-to-Many',
                    related_name='asym_self_m2ms',
                    related_query_name='reverse_asym_self_m2m',
                    to='app.M',
                    verbose_name='Asymmetrical Self Many-to-Many')),

                ('sym_self_m2m',
                 models.ManyToManyField(
                    blank=True,
                    db_index=True,
                    default=None,
                    help_text='Symmetrical Self Many-to-Many',
                    related_name='_m_sym_self_m2m_+',
                    related_query_name='+',
                    to='app.M',
                    verbose_name='Symmetrical Self Many-to-Many'))
            ],

            options={
                'verbose_name': 'M',
                'verbose_name_plural': 'Ms',
                'db_table': 'M',
                'default_related_name': 'ms'
            }
        )
    ]
