# Generated by Django 3.1.4 on 2020-12-17 21:48


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = ('app', '0001_initial'),

    operations = [
        migrations.AlterModelOptions(
            name='m0',
            options={
                'default_related_name': 'm0s',
                'ordering': ('f0',),
                'verbose_name': 'M0',
                'verbose_name_plural': 'M0s'
            }
        ),

        migrations.AlterModelOptions(
            name='m1',
            options={
                'default_related_name': 'm1s',
                'ordering': ('f1',),
                'verbose_name': 'M1',
                'verbose_name_plural': 'M1s'
            }
        ),

        migrations.AlterModelOptions(
            name='m1a',
            options={
                'default_related_name': 'm1as',
                'ordering': ('f1a',),
                'verbose_name': 'M1A',
                'verbose_name_plural': 'M1As'
            }
        ),

        migrations.AlterModelOptions(
            name='m2',
            options={
                'default_related_name': 'm2s',
                'ordering': ('f2',),
                'verbose_name': 'M2',
                'verbose_name_plural': 'M2s'
            }
        ),

        migrations.AlterModelOptions(
            name='m2a',
            options={
                'default_related_name': 'm2as',
                'ordering': ('f2a',),
                'verbose_name': 'M2A',
                'verbose_name_plural': 'M2As'
            }
        ),

        migrations.AlterModelOptions(
            name='m2b',
            options={
                'default_related_name': 'm2bs',
                'ordering': ('f2b',),
                'verbose_name': 'M2B',
                'verbose_name_plural': 'M2Bs'
            }
        )
    ]
